[package]
name = "blue-candle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
mkl = ["dep:intel-mkl-src", "candle-core/mkl", "candle-nn/mkl"]

default = []
cuda = ["candle-core/cuda", "candle-nn/cuda"]
[dependencies]

anyhow = "1"
axum = { version = "0", features = ["multipart"] }
candle-core = "0"
candle-nn = "0"
clap = { version = "4", features = ["derive"] }
futures = "0"
intel-mkl-src = { version = "0", optional = true }
hf-hub = { version = "0", features = ["tokio"] }
image = "0"
imageproc = "0"
reqwest = { version = "0", features = ["stream", "multipart", "json"] }
rusttype = "0"
serde = "1"
tokio = { version = "1", features = [
    "fs",
    "io-util",
    "macros",
    "rt-multi-thread",
] }
tokio-util = { version = "0", features = ["codec"] }
tracing = "0"
tracing-subscriber = "0"
uuid = { version = "1", features = ["v4"] }

zune-jpeg = "*"
zune-core = "*"
fast_image_resize = "*"
